- name: Install registry
  yum: name={{ item }} state=present
  with_items:
  - yunion-registry
  when:
  - is_centos_based is defined
  - non_iso_mode is defined

- name: Create yunion directory
  file:
    name: /etc/yunion/
    state: directory

- name: Config registry
  template: src=registry.yml dest=/etc/yunion/registry.yml
  notify: restart registry

- name: Start registry service
  service: name=yunion-registry state=started enabled=yes
